#!/bin/sh

packagersgroup="<%= packagers_group %>"
createsrpm="<%= createsrpm_path %>"

function isingroup()
{
  grp="$1"
  for group in `groups`
  do if [ "$grp" = "$group" ]
     then 
        return 0
     fi
  done
  return 1
}

if ! isingroup "$packagersgroup"
then
   echo "You are not in $packagersgroup group."
   exit 1
fi

exec $createsrpm $*

